## 1. 붓꽃의 품종 분류
###### - 가정 : 들에서 발견한 붓꽃의 품종을 알고싶을때
###### - 목표 : 어떤 품종인지 구분해놓은 측정 데이터를 이용하여 새로 채집한 붓꽃의 품종을 예측하는 머신러닝 모델 만들기
###### - 지도학습 : 붓꽃의 품종을 정확하게 분류한 데이터를 가지고 있음
###### - 3개의 클래스를 분류하는 문제 : 데이터셋에 있는 붓꽃데이터가 모두 세 클래스(출력될수있는값:붓꽃의종류) 중 하나에 속하기 때문

### 1) 데이터로딩 및 속성확인

In [1]:
from sklearn.datasets import load_iris

In [2]:
iris_dataset = load_iris() #샘플데이터 로드

In [3]:
print("iris_dataset의 키 : \n{}".format(iris_dataset.keys()))
type(iris_dataset) #파이썬의 딕셔너리와 유사한 bunch클래스 객체

iris_dataset의 키 : 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


sklearn.utils.Bunch

In [4]:
print(iris_dataset['DESCR'][:193] + "\n...") #데이터셋에 대한 간략설명

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive att
...


In [5]:
print("타깃의 이름 : {}".format(iris_dataset['target_names'])) #종속변수 : 우리가 예측하려는 붓꽃품종의 이름을 문자열배열로 가지고있음

타깃의 이름 : ['setosa' 'versicolor' 'virginica']


In [6]:
print("특성의 이름 : \n{}".format(iris_dataset['feature_names'])) #독립변수 : 각 특성을 설명

특성의 이름 : 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [7]:
print("data 타입 : {}".format(type(iris_dataset['data']))) # 실제데이터는 'target'과 'data'에 Numpy 배열형태로 있음

data 타입 : <class 'numpy.ndarray'>


In [8]:
print("data 크기 : {}".format(iris_dataset['data'].shape)) #데이터 배열의 행은 개개의 꽃이 되며 열은 각 꽃에서 구한 네개의 측정치

data 크기 : (150, 4)


In [9]:
print("data의 처음 다섯행 : \n{}".format(iris_dataset['data'][:5]))

data의 처음 다섯행 : 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [11]:
print("target의 타입 : {}".format(type(iris_dataset['target'])))

target의 타입 : <class 'numpy.ndarray'>


In [12]:
print("target의 크기 : {}".format(iris_dataset['target'].shape))

target의 크기 : (150,)


In [13]:
print("타깃\n{}".format(iris_dataset['target']))

타깃
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


### 2) 데이터 분리 : train, test

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state=0)

In [17]:
print("X_Train 크기 : {}".format(X_train.shape)) #75%
print("y_Train 크기 : {}".format(y_train.shape))

X_Train 크기 : (112, 4)
y_Train 크기 : (112,)


In [18]:
print("X_test 크기 : {}".format(X_test.shape)) #25%
print("y_test 크기 : {}".format(y_test.shape))

X_test 크기 : (38, 4)
y_test 크기 : (38,)


In [19]:
iris_dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [20]:
import pandas as pd
iris_df = pd.DataFrame(X_train, columns=iris_dataset.feature_names) #X_train데이터를 사용하여 데이터프레임 만듬

In [21]:
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.9               3.0                4.2               1.5
1                5.8               2.6                4.0               1.2
2                6.8               3.0                5.5               2.1
3                4.7               3.2                1.3               0.2
4                6.9               3.1                5.1               2.3

### 3) 데이터 살펴보기

In [29]:
np.round(iris_df.corr(),3)

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)              1.000            -0.055              0.887   
sepal width (cm)              -0.055             1.000             -0.356   
petal length (cm)              0.887            -0.356              1.000   
petal width (cm)               0.839            -0.300              0.967   

                   petal width (cm)  
sepal length (cm)             0.839  
sepal width (cm)             -0.300  
petal length (cm)             0.967  
petal width (cm)              1.000

In [22]:
#y_train에 따라 색으로 구분되는 산점도 행렬
pd.plotting.scatter_matrix(iris_df, #독립변수
                           c=y_train, #종속변수
                           figsize=(15,15), 
                           marker='o', 
                           hist_kwds={'bins':20}, 
                           s=60, alpha=0.8)

array([[<matplotlib.axes._subplots.AxesSubplot object at 0x00000209D3516048>,
      dtype=object)

### 4) 머신러닝 모델 : k-최근접 이웃 알고리즘

In [23]:
from sklearn.neighbors import KNeighborsClassifier

# knn객체 : 훈련데이터로 모델을 만들고 새로운 데이터포인트에 대해 예측하는 알고리즘을 캡슐화
# 또한 알고리즘이 훈련데이터로부터 추출한 정보를 담고 있음
# KNeighborsClassifier : 훈련데이터 자체를 저장
knn = KNeighborsClassifier(n_neighbors=1) # n_neighbor : 이웃의 갯수
print(knn)

# fit() : 훈련데이터셋으로부터 모델 만들기, knn객체 자체를 반환, 그리고 knn객체 자체를 변경시킴, knn객체가 문자열 형태로 출력됨
#출력에서 모델으르생성할떄 사용한 매개변수 확인 가능
# 훈련데이터(Numpy배열 X_train), 훈련데이터레이블(Numpy배열 y_train)을 매개변수로 받음
knn.fit(X_train, y_train)
print(knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


### 5) 예측

In [24]:
import numpy as np
X_new = np.array([[5,2.9,1,0.2]]) #정확한레이블을 모르는 새데이터
print("X_new.shape : {}".format(X_new.shape))

X_new.shape : (1, 4)


In [25]:
prediction = knn.predict(X_new) #훈련된 모델(knn)을 사용하여 새데이터의 레이블 예측(predict)
print("예측 : {}".format(prediction))
print("예측한 타깃의 이름 : {}".format(iris_dataset['target_names'][prediction]))

예측 : [0]
예측한 타깃의 이름 : ['setosa']


In [26]:
#테스트데이터 사용 (모델을 만들때 사용하지 않았고, 테스트셋에 있는 각 붓꽃의 품종을 정확히 알고있음)
y_pred = knn.predict(X_test) 
print("테스트 셋에 대한 예측값: {}".format(y_pred))

테스트 셋에 대한 예측값: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


### 6) 검증

In [27]:
# 예측값 y_pred와 기존의 정답인 y_test가 맞는지 확인
print("테스트 셋에 대한 정확도 : {:.2f}".format(np.mean(y_pred == y_test)))

테스트 셋에 대한 정확도 : 0.97


In [28]:
print("테스트 셋트에 대한 정확도 : {:.2f}".format(knn.score(X_test, y_test)))

테스트 셋트에 대한 정확도 : 0.97
